project_name: "Automatic_Guitar_Transcription" 
experiment_name: "transformer_SynthTab" 

dataset: "GuitarSet" 

feature_definitions:
  cqt:
    key: "cqt"
    in_channels: 1
    num_freq: 144
  hcqt:
    key: "hcqt"
    in_channels: 6
    num_freq: 144
  melspec:
    key: "melspec"
    in_channels: 1
    num_freq: 256

dataset_configs:
  GuitarSet:
    drive_data_path: "/content/drive/MyDrive/Automatic Guitar Transcription/feature_extraction/guitarset_all_npz/"
    local_data_path: "/content/local_guitarset_data/"
    active_feature: "hcqt"
    supported_features: ["cqt", "hcqt", "melspec"]
  SynthTab:
    drive_data_path: "/content/drive/MyDrive/Automatic Guitar Transcription/feature_extraction/synthtab_all_npz/most_active_frames/"
    local_data_path: "/content/local_synthtab_data/"
    active_feature: "hcqt"
    supported_features: ["cqt", "hcqt", "melspec"]

data:
  window_size: 200 
  batch_size: 30 
  validation_split_size: 0.2 
  random_state: 42 
  num_workers: 4 
  max_fret: 19 
  include_silence: True 

model:
  name: "Transformer" 
  params:
    num_strings: 6 
    d_model: 256
    n_head: 8 
    num_encoder_layers: 6 
    dim_feedforward: 1024 
    dropout: 0.1 

loss:
  use_class_weights: True #
  class_weights_silence_factor: 0.25 #
  use_focal: True #
  focal_loss_gamma: 2.0 #

training:
  optimizer:
    active_optimizer: "Adam" 
    configurations:
      Adam:
        params:
          lr: 0.0005 
      AdamW:
        params:
          lr: 0.0005 
          weight_decay: 0.01 

  epochs: 60 
  device: "cuda" 
  use_mixed_precision: True 

  early_stopping:
    enabled: True 
    monitor: "val_f1" 
    patience: 5 
    min_delta: 0.0001 
    mode: "max" 

  logging_and_checkpointing:
    use_tensorboard: True 
    resume_from_checkpoint: null 
    save_epoch_checkpoint_interval: 15 

  scheduler:
    active_scheduler: "StepLR" 
    configurations:
      ReduceLROnPlateau:
        params:
          monitor: "val_f1" 
          mode: "max" 
          factor: 0.2 
          patience: 5 
          verbose: True 
          min_lr: 0.000001 
      StepLR:
        params:
          step_size: 10 
          gamma: 0.5 
          verbose: True 